Added support for routes via interface
inmanta/nfv-test-api pull request #18
Opened 2020-10-09 09:41 UTC by sanderr

closes #16

2020-10-09 11:43 UTC, andraskvr requested changes

2020-10-09 11:43 UTC, andraskvr commented on tests/test_server.py
> +        def add_delete_route(
Could you improve the naming here a bit?

2020-10-09 11:48 UTC, sanderr commented
I just realized I forgot to add tests for the simulation case. Will do.

2020-10-09 13:06 UTC, andraskvr approved these changes

2020-10-14 08:48 UTC, bartv approved these changes

2020-10-14 08:52 UTC, merged