RAN support
inmanta/nfv-test-api pull request #46
Opened 2023-07-25 15:11 UTC by DariushMoh

# Description

GNodeB/UE support added, for configuration management and UERANSIM client support.

Related to [solutions/tickets#57](https://code.inmanta.com/solutions/tickets/-/issues/57)

# Reviewers list 

- [ ] @guillaume.everartsdevelp 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Correct, in line with design
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented (classes, methods and function docs, document important assumptions, link to reference materials)
- [ ] Type annotations
- [ ] Issue is in the review column
- [x] MR is assigned to first reviewer

2023-07-25 15:35 UTC, edvgui requested changes
I didn't make a full review yet.  Some general comments:
1. Can you use `pathlib` a bit more? For concatenating path, reading files, etc.
2. Can you update the openapi file in the repo? It would make it easier to get an overview of how the api actually looks
3. Can you extract and reuse all the logic you have to read/create files related to the gnodeb?  You build the same paths in multiple places

2023-07-25 15:35 UTC, edvgui commented on src/nfv_test_api/config.py
> +        gnb_config_folder.mkdir()
```suggestion
    gnb_config_folder.mkdir(parents=True, exists_ok=True)
```
You can simplify this like this

2023-07-25 15:35 UTC, edvgui commented on src/nfv_test_api/v2/services/gnodeb.py
> +        config_file_path = Config().gnb_config_folder+"gnb_"+identifier+".yml"
This is a bit asking for problems, use pathlib here as well

2023-07-25 15:35 UTC, edvgui commented on src/nfv_test_api/v2/services/gnodeb.py
> +        out = open(out_file_path,"w")
In most cases you will actually create that file
```suggestion
        out = open(out_file_path,"w+")
```

2023-07-26 12:02 UTC, edvgui commented on src/nfv_test_api/v2/controllers/gnodeb.py
> +    @namespace.response(HTTPStatus.OK, "Found a gNodeB config with a matching nci", gnodeb_model)
![image](https://github.com/inmanta/nfv-test-api/assets/20844316/16322920-15e0-4375-a589-61fa38dfc34e)
I guess this is not what the api really returns

2023-07-26 12:13 UTC, DariushMoh commented on src/nfv_test_api/v2/controllers/gnodeb.py
> +    @namespace.response(HTTPStatus.OK, "Found a gNodeB config with a matching nci", gnodeb_model)
Indeed the start only returns status code

2023-07-26 12:14 UTC, DariushMoh commented on src/nfv_test_api/v2/controllers/gnodeb.py
> +    @namespace.response(HTTPStatus.OK, "Found a gNodeB config with a matching nci", gnodeb_model)
I will modify the header of the controller

2023-07-26 12:14 UTC, DariushMoh commented on src/nfv_test_api/v2/services/gnodeb.py
> +        path = Path(Config().gnb_log_folder) / filename
should I raise an error ?

2023-07-26 12:15 UTC, DariushMoh commented on src/nfv_test_api/v2/services/gnodeb.py
> +            del self.processes[identifier]
Then nothing happens and it returns code 200. Should I raise NotFound error ?

2023-07-26 15:31 UTC, edvgui approved these changes
Looks good

2023-07-26 15:31 UTC, edvgui commented on src/nfv_test_api/v2/services/gnodeb.py
> +            del self.processes[identifier]
I guess yes

2023-07-26 16:10 UTC, merged